/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semana_3;

/**
 *
 * @author Sebas
 */
public class Ejercicio03 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio03
     */
    public Ejercicio03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        btnProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Minutos de Tardanza:");

        jLabel2.setText("N° de Observación:");

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        btnProcesar.setText("PROCESAR");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnProcesar)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProcesar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        
        int minutos,observacion, puntajeP,puntajeO,puntajeTotal;
        double bonificacion;
        
        minutos = leerMinutos();
        observacion = leerObservacion();
        puntajeP = obtenerPuntajePuntualidad(minutos);
        puntajeO = obtenerPuntajeObservacion(observacion);
        puntajeTotal = calcularPuntajeTotal(puntajeP,puntajeO);
        bonificacion = calcularBonificacion(puntajeTotal);
        txtSalida.setText(null);
        mostrarResultados(puntajeP,puntajeO,puntajeTotal,bonificacion);
    }//GEN-LAST:event_btnProcesarActionPerformed

    
    int leerMinutos(){
        return Integer.parseInt(txtMinutos.getText());
    }
    int leerObservacion(){
        return Integer.parseInt(txtObservacion.getText());
    }
    int obtenerPuntajePuntualidad(int minutos){
        int puntaje;
        switch(minutos){
            case 0: puntaje = 10;
                break;
            case 1:    
            case 2: puntaje = 8;
                break;
            case 3:
            case 4:
            case 5: puntaje = 6;
                break;
            case 6:
            case 7:
            case 8:
            case 9: puntaje = 4;
                break;
            default: puntaje = 0;
        }
        return puntaje;
    }
    
    int obtenerPuntajeObservacion(int observacion){
            int puntaje;
            switch(observacion){
                case 0: puntaje = 10;
                    break;
                case 1: puntaje = 8;
                    break;
                case 2: puntaje = 5;
                    break;
                case 3: puntaje = 1;
                    break;    
                default: puntaje = 0;
            }
            
            return puntaje;
    }
    
    int calcularPuntajeTotal(int puntajePuntualidad, int puntajeObservacion){
        return puntajePuntualidad + puntajeObservacion;
    }
    double calcularBonificacion(int puntajeTotal){
        double bonificacion;
        
        if(puntajeTotal<11){
            bonificacion = 2.5*puntajeTotal;
        }else if(puntajeTotal<=13){
            bonificacion = 5*puntajeTotal;
        }else if(puntajeTotal<=16){
            bonificacion = 7.5*puntajeTotal;   
        }else if(puntajeTotal<=19){
            bonificacion = 10*puntajeTotal;
        }else {
            bonificacion = 12.5*puntajeTotal;
        }
        return bonificacion;
    }
    
    void imprimir(String texto){
        txtSalida.append(texto+"\n");
    }
    void mostrarResultados(int puntualidad, int observacion, int total, double bono){
        imprimir("Puntaje por puntualidad: "+puntualidad);
        imprimir("Puntaje por observaciones: "+observacion);
        imprimir("Puntaje total: "+total);
        imprimir("Bonoficación: "+bono);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
